name: 刷步数

on:
  schedule:
    - cron: '12 0,2,6,8,14 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout codes
        uses: actions/checkout@v3

      - name: Update system and install zsh
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y
          
      - name: 初始化Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          
      - name: 开始
        env:
          CONFIG: ${{ secrets.CONFIG }}
        run: |
          pip3 install requests pytz
          python3 main.py || true
          echo "---- 网络测试 ----"
          curl -I https://wzz.wangzouzou.com/motion/api/motion/Xiaomi || true

      - name: 提交更新
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "更新步数数据"
          git push
